version: "3"

services:
  web_service:
    container_name: django-web-service
    image: django-web-service:python3.8
    build:
      context: ../
      dockerfile: docker/Dockerfile
    volumes:
      - ../web_service:/code:cached
    command: ["python", "manage.py", "runserver", "0.0.0.0:8000"]
    ports:
      - "8000:8000"
    env_file:
      - ../.env
